// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: src/proto/emoney/emoney.proto

package emoney

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_emoney_emoney_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_emoney_emoney_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_src_proto_emoney_emoney_proto_rawDescGZIP(), []int{0}
}

type GetWalletProfileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNumber string `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
}

func (x *GetWalletProfileRequest) Reset() {
	*x = GetWalletProfileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_emoney_emoney_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWalletProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletProfileRequest) ProtoMessage() {}

func (x *GetWalletProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_emoney_emoney_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletProfileRequest.ProtoReflect.Descriptor instead.
func (*GetWalletProfileRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_emoney_emoney_proto_rawDescGZIP(), []int{1}
}

func (x *GetWalletProfileRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type GetWalletProfileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RessponseCode   int64                                             `protobuf:"varint,1,opt,name=ressponseCode,proto3" json:"ressponseCode,omitempty"`
	ResponseMessage string                                            `protobuf:"bytes,2,opt,name=responseMessage,proto3" json:"responseMessage,omitempty"`
	ResponseData    *GetWalletProfileResponse_AdditionalWalletProfile `protobuf:"bytes,3,opt,name=responseData,proto3" json:"responseData,omitempty"`
}

func (x *GetWalletProfileResponse) Reset() {
	*x = GetWalletProfileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_emoney_emoney_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWalletProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletProfileResponse) ProtoMessage() {}

func (x *GetWalletProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_emoney_emoney_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletProfileResponse.ProtoReflect.Descriptor instead.
func (*GetWalletProfileResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_emoney_emoney_proto_rawDescGZIP(), []int{2}
}

func (x *GetWalletProfileResponse) GetRessponseCode() int64 {
	if x != nil {
		return x.RessponseCode
	}
	return 0
}

func (x *GetWalletProfileResponse) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

func (x *GetWalletProfileResponse) GetResponseData() *GetWalletProfileResponse_AdditionalWalletProfile {
	if x != nil {
		return x.ResponseData
	}
	return nil
}

type GetWalletInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNumber string `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
}

func (x *GetWalletInfoRequest) Reset() {
	*x = GetWalletInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_emoney_emoney_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWalletInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletInfoRequest) ProtoMessage() {}

func (x *GetWalletInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_emoney_emoney_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletInfoRequest.ProtoReflect.Descriptor instead.
func (*GetWalletInfoRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_emoney_emoney_proto_rawDescGZIP(), []int{3}
}

func (x *GetWalletInfoRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type GetWalletInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RessponseCode   int64                                       `protobuf:"varint,1,opt,name=ressponseCode,proto3" json:"ressponseCode,omitempty"`
	ResponseMessage string                                      `protobuf:"bytes,2,opt,name=responseMessage,proto3" json:"responseMessage,omitempty"`
	ResponseData    *GetWalletInfoResponse_AdditionalWalletInfo `protobuf:"bytes,3,opt,name=responseData,proto3" json:"responseData,omitempty"`
}

func (x *GetWalletInfoResponse) Reset() {
	*x = GetWalletInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_emoney_emoney_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWalletInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletInfoResponse) ProtoMessage() {}

func (x *GetWalletInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_emoney_emoney_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletInfoResponse.ProtoReflect.Descriptor instead.
func (*GetWalletInfoResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_emoney_emoney_proto_rawDescGZIP(), []int{4}
}

func (x *GetWalletInfoResponse) GetRessponseCode() int64 {
	if x != nil {
		return x.RessponseCode
	}
	return 0
}

func (x *GetWalletInfoResponse) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

func (x *GetWalletInfoResponse) GetResponseData() *GetWalletInfoResponse_AdditionalWalletInfo {
	if x != nil {
		return x.ResponseData
	}
	return nil
}

type InsertTransactionHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNumber         string `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	CategoryTransaction string `protobuf:"bytes,3,opt,name=categoryTransaction,proto3" json:"categoryTransaction,omitempty"`
	NominalTransaction  string `protobuf:"bytes,4,opt,name=nominalTransaction,proto3" json:"nominalTransaction,omitempty"`
	SecurityCode        string `protobuf:"bytes,8,opt,name=securityCode,proto3" json:"securityCode,omitempty"`
	FeeTransaction      string `protobuf:"bytes,10,opt,name=feeTransaction,proto3" json:"feeTransaction,omitempty"`
}

func (x *InsertTransactionHistoryRequest) Reset() {
	*x = InsertTransactionHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_emoney_emoney_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertTransactionHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertTransactionHistoryRequest) ProtoMessage() {}

func (x *InsertTransactionHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_emoney_emoney_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertTransactionHistoryRequest.ProtoReflect.Descriptor instead.
func (*InsertTransactionHistoryRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_emoney_emoney_proto_rawDescGZIP(), []int{5}
}

func (x *InsertTransactionHistoryRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *InsertTransactionHistoryRequest) GetCategoryTransaction() string {
	if x != nil {
		return x.CategoryTransaction
	}
	return ""
}

func (x *InsertTransactionHistoryRequest) GetNominalTransaction() string {
	if x != nil {
		return x.NominalTransaction
	}
	return ""
}

func (x *InsertTransactionHistoryRequest) GetSecurityCode() string {
	if x != nil {
		return x.SecurityCode
	}
	return ""
}

func (x *InsertTransactionHistoryRequest) GetFeeTransaction() string {
	if x != nil {
		return x.FeeTransaction
	}
	return ""
}

type InsertTransactionHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RessponseCode   int64  `protobuf:"varint,1,opt,name=ressponseCode,proto3" json:"ressponseCode,omitempty"`
	ResponseMessage string `protobuf:"bytes,2,opt,name=responseMessage,proto3" json:"responseMessage,omitempty"`
	ResponseData    string `protobuf:"bytes,3,opt,name=responseData,proto3" json:"responseData,omitempty"`
}

func (x *InsertTransactionHistoryResponse) Reset() {
	*x = InsertTransactionHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_emoney_emoney_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertTransactionHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertTransactionHistoryResponse) ProtoMessage() {}

func (x *InsertTransactionHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_emoney_emoney_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertTransactionHistoryResponse.ProtoReflect.Descriptor instead.
func (*InsertTransactionHistoryResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_emoney_emoney_proto_rawDescGZIP(), []int{6}
}

func (x *InsertTransactionHistoryResponse) GetRessponseCode() int64 {
	if x != nil {
		return x.RessponseCode
	}
	return 0
}

func (x *InsertTransactionHistoryResponse) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

func (x *InsertTransactionHistoryResponse) GetResponseData() string {
	if x != nil {
		return x.ResponseData
	}
	return ""
}

type GetWalletProfileResponse_AdditionalWalletProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber string `protobuf:"bytes,2,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Email       string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *GetWalletProfileResponse_AdditionalWalletProfile) Reset() {
	*x = GetWalletProfileResponse_AdditionalWalletProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_emoney_emoney_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWalletProfileResponse_AdditionalWalletProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletProfileResponse_AdditionalWalletProfile) ProtoMessage() {}

func (x *GetWalletProfileResponse_AdditionalWalletProfile) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_emoney_emoney_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletProfileResponse_AdditionalWalletProfile.ProtoReflect.Descriptor instead.
func (*GetWalletProfileResponse_AdditionalWalletProfile) Descriptor() ([]byte, []int) {
	return file_src_proto_emoney_emoney_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GetWalletProfileResponse_AdditionalWalletProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetWalletProfileResponse_AdditionalWalletProfile) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *GetWalletProfileResponse_AdditionalWalletProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetWalletInfoResponse_AdditionalWalletInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExpTier      string `protobuf:"bytes,1,opt,name=expTier,proto3" json:"expTier,omitempty"`
	Ballance     string `protobuf:"bytes,2,opt,name=ballance,proto3" json:"ballance,omitempty"`
	WalletPoint  string `protobuf:"bytes,3,opt,name=walletPoint,proto3" json:"walletPoint,omitempty"`
	WalletStatus string `protobuf:"bytes,4,opt,name=walletStatus,proto3" json:"walletStatus,omitempty"`
	SecurityCode string `protobuf:"bytes,5,opt,name=securityCode,proto3" json:"securityCode,omitempty"`
	WalletId     string `protobuf:"bytes,6,opt,name=walletId,proto3" json:"walletId,omitempty"`
}

func (x *GetWalletInfoResponse_AdditionalWalletInfo) Reset() {
	*x = GetWalletInfoResponse_AdditionalWalletInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_emoney_emoney_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWalletInfoResponse_AdditionalWalletInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletInfoResponse_AdditionalWalletInfo) ProtoMessage() {}

func (x *GetWalletInfoResponse_AdditionalWalletInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_emoney_emoney_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletInfoResponse_AdditionalWalletInfo.ProtoReflect.Descriptor instead.
func (*GetWalletInfoResponse_AdditionalWalletInfo) Descriptor() ([]byte, []int) {
	return file_src_proto_emoney_emoney_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetWalletInfoResponse_AdditionalWalletInfo) GetExpTier() string {
	if x != nil {
		return x.ExpTier
	}
	return ""
}

func (x *GetWalletInfoResponse_AdditionalWalletInfo) GetBallance() string {
	if x != nil {
		return x.Ballance
	}
	return ""
}

func (x *GetWalletInfoResponse_AdditionalWalletInfo) GetWalletPoint() string {
	if x != nil {
		return x.WalletPoint
	}
	return ""
}

func (x *GetWalletInfoResponse_AdditionalWalletInfo) GetWalletStatus() string {
	if x != nil {
		return x.WalletStatus
	}
	return ""
}

func (x *GetWalletInfoResponse_AdditionalWalletInfo) GetSecurityCode() string {
	if x != nil {
		return x.SecurityCode
	}
	return ""
}

func (x *GetWalletInfoResponse_AdditionalWalletInfo) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

var File_src_proto_emoney_emoney_proto protoreflect.FileDescriptor

var file_src_proto_emoney_emoney_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6d, 0x6f, 0x6e,
	0x65, 0x79, 0x2f, 0x65, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x65, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3b, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x57, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x22, 0xaf, 0x02, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x5c, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x65, 0x6d, 0x6f, 0x6e, 0x65, 0x79,
	0x2e, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x1a,
	0x65, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x57, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x38, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x22, 0x94, 0x03, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65,
	0x73, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x56, 0x0a, 0x0c, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x32, 0x2e, 0x65, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x1a, 0xd2, 0x01, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x78, 0x70, 0x54, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x78,
	0x70, 0x54, 0x69, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x6c, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x6c, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x77, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x63, 0x75, 0x72,
	0x69, 0x74, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x77,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x64, 0x22, 0xf1, 0x01, 0x0a, 0x1f, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x30, 0x0a,
	0x13, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2e, 0x0a, 0x12, 0x6e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x6e, 0x6f, 0x6d,
	0x69, 0x6e, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x22, 0x0a, 0x0c, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x66, 0x65, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x66, 0x65, 0x65,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x96, 0x01, 0x0a, 0x20,
	0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x32, 0xa2, 0x02, 0x0a, 0x0d, 0x45, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1f, 0x2e, 0x65, 0x6d, 0x6f,
	0x6e, 0x65, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x65, 0x6d,
	0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1c, 0x2e, 0x65, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x65, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x68, 0x0a, 0x11, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x2e, 0x65, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x49, 0x6e,
	0x73, 0x65, 0x72, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e,
	0x65, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x2f, 0x73, 0x72,
	0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_proto_emoney_emoney_proto_rawDescOnce sync.Once
	file_src_proto_emoney_emoney_proto_rawDescData = file_src_proto_emoney_emoney_proto_rawDesc
)

func file_src_proto_emoney_emoney_proto_rawDescGZIP() []byte {
	file_src_proto_emoney_emoney_proto_rawDescOnce.Do(func() {
		file_src_proto_emoney_emoney_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_proto_emoney_emoney_proto_rawDescData)
	})
	return file_src_proto_emoney_emoney_proto_rawDescData
}

var file_src_proto_emoney_emoney_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_src_proto_emoney_emoney_proto_goTypes = []interface{}{
	(*EmptyMessage)(nil),                                     // 0: emoney.EmptyMessage
	(*GetWalletProfileRequest)(nil),                          // 1: emoney.GetWalletProfileRequest
	(*GetWalletProfileResponse)(nil),                         // 2: emoney.GetWalletProfileResponse
	(*GetWalletInfoRequest)(nil),                             // 3: emoney.GetWalletInfoRequest
	(*GetWalletInfoResponse)(nil),                            // 4: emoney.GetWalletInfoResponse
	(*InsertTransactionHistoryRequest)(nil),                  // 5: emoney.InsertTransactionHistoryRequest
	(*InsertTransactionHistoryResponse)(nil),                 // 6: emoney.InsertTransactionHistoryResponse
	(*GetWalletProfileResponse_AdditionalWalletProfile)(nil), // 7: emoney.GetWalletProfileResponse.AdditionalWalletProfile
	(*GetWalletInfoResponse_AdditionalWalletInfo)(nil),       // 8: emoney.GetWalletInfoResponse.AdditionalWalletInfo
}
var file_src_proto_emoney_emoney_proto_depIdxs = []int32{
	7, // 0: emoney.GetWalletProfileResponse.responseData:type_name -> emoney.GetWalletProfileResponse.AdditionalWalletProfile
	8, // 1: emoney.GetWalletInfoResponse.responseData:type_name -> emoney.GetWalletInfoResponse.AdditionalWalletInfo
	1, // 2: emoney.EmoneyService.GetWalletProfile:input_type -> emoney.GetWalletProfileRequest
	3, // 3: emoney.EmoneyService.GetWalletInfo:input_type -> emoney.GetWalletInfoRequest
	5, // 4: emoney.EmoneyService.InsertTransaction:input_type -> emoney.InsertTransactionHistoryRequest
	2, // 5: emoney.EmoneyService.GetWalletProfile:output_type -> emoney.GetWalletProfileResponse
	4, // 6: emoney.EmoneyService.GetWalletInfo:output_type -> emoney.GetWalletInfoResponse
	6, // 7: emoney.EmoneyService.InsertTransaction:output_type -> emoney.InsertTransactionHistoryResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_proto_emoney_emoney_proto_init() }
func file_src_proto_emoney_emoney_proto_init() {
	if File_src_proto_emoney_emoney_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_proto_emoney_emoney_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_emoney_emoney_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWalletProfileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_emoney_emoney_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWalletProfileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_emoney_emoney_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWalletInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_emoney_emoney_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWalletInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_emoney_emoney_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertTransactionHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_emoney_emoney_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertTransactionHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_emoney_emoney_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWalletProfileResponse_AdditionalWalletProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_emoney_emoney_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWalletInfoResponse_AdditionalWalletInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_proto_emoney_emoney_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_emoney_emoney_proto_goTypes,
		DependencyIndexes: file_src_proto_emoney_emoney_proto_depIdxs,
		MessageInfos:      file_src_proto_emoney_emoney_proto_msgTypes,
	}.Build()
	File_src_proto_emoney_emoney_proto = out.File
	file_src_proto_emoney_emoney_proto_rawDesc = nil
	file_src_proto_emoney_emoney_proto_goTypes = nil
	file_src_proto_emoney_emoney_proto_depIdxs = nil
}
